version: 2

sources: 
  - name : addictions
    database : projet-final-le-wagon
    schema: bdd_projet
    tables:
      - name: comorbidites_2020_2022
      - name: depenses_medicaments_2020
      - name: depenses_medicaments_2021
      - name: depenses_medicaments_2022
      - name: depenses_soins_maladies_psychiatriques_2020_2022_actes
      - name: depenses_soins_maladies_psychiatriques_2020_2022_sous_totaux
      - name: dept_region_name
      - name: effectifs_clean
      - name: effectifs_clean_V2
      - name: for_mapping_V1
      - name: liste_medecins_psychiatres
      - name: offre_soins_cleaned
      - name: repartition_psychiatre

