version: 2

sources: 
  - name: bdd_projet
    tables: 
      - name: Depenses_par_actes
        identifier: Analyse des depenses par actes
      - name: pop_france_2023
      - name: prev_by_age
        identifier: prev_by_age
      - name: repartition_psychiatre
        identifier: repartition_psychiatre
      - name: taux_chomage_dep_20_21_22
        identifier: taux_chomage_departement_2020_2021_2022
      - name : Analyse_depenses_brutes
        identifier: Analyse_dep_distribution
      - name : Commorbidites
        identifier: comorbidites_2020_2022
      - name : Depenses_medicaments_2020
        identifier: depenses_medicaments_2020
      - name : Depenses_medicaments_2021
        identifier: depenses_medicaments_2021
      - name : Depenses medicaments_2022
        identifier : depenses_medicaments_2022
      - name: dept_region_name
      - name: effectifs_clean_V3
        identifier: effectifs
      - name: equipements_culturels_france
      - name: etudes_superieures
        identifier: etudes_supp
      - name: offre_soins
        identifier: offre_soins_cleaned
      - name: taux_chomage_region
        identifier: taux_chomage_region_2020_2021_2022
      - name: universitées
        identifier: universities
      - name: taux_pauvreté
        identifier: tx_pauvrete
      - name: etablissements_sportifs
        
